version: "3.7"

services:
  authdb:
    build: 
      context: .
      dockerfile: Dockerfile.postgres.dev
    ports:
      - "5432:5432"
  auth-server:
    build: 
      context: .
      dockerfile: Dockerfile.node.dev
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
